apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 195.89.108.194/32
  ports:
  - port: 80
    targetPort: 4567
  selector:
    app: frontend
